// ClusterTimezoneType.cs
//
// This generated file is part of the Rubrik PowerShell SDK.
// Manual changes to this file may be lost.

#nullable enable
using System;
using System.Collections.Generic;
using System.Text;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace RubrikSecurityCloud.Types
{
    public enum ClusterTimezoneType
    {
        [EnumMember(Value = "CLUSTER_TIMEZONE_AFRICA_ABIDJAN")]
        CLUSTER_TIMEZONE_AFRICA_ABIDJAN,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AFRICA_ALGIERS")]
        CLUSTER_TIMEZONE_AFRICA_ALGIERS,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AFRICA_BISSAU")]
        CLUSTER_TIMEZONE_AFRICA_BISSAU,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AFRICA_CEUTA")]
        CLUSTER_TIMEZONE_AFRICA_CEUTA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AFRICA_JOHANNESBURG")]
        CLUSTER_TIMEZONE_AFRICA_JOHANNESBURG,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AFRICA_LAGOS")]
        CLUSTER_TIMEZONE_AFRICA_LAGOS,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AFRICA_MAPUTO")]
        CLUSTER_TIMEZONE_AFRICA_MAPUTO,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AFRICA_MONROVIA")]
        CLUSTER_TIMEZONE_AFRICA_MONROVIA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AFRICA_NAIROBI")]
        CLUSTER_TIMEZONE_AFRICA_NAIROBI,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AFRICA_NDJAMENA")]
        CLUSTER_TIMEZONE_AFRICA_NDJAMENA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AFRICA_SAO_TOME")]
        CLUSTER_TIMEZONE_AFRICA_SAO_TOME,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AFRICA_TRIPOLI")]
        CLUSTER_TIMEZONE_AFRICA_TRIPOLI,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AFRICA_TUNIS")]
        CLUSTER_TIMEZONE_AFRICA_TUNIS,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AFRICA_WINDHOEK")]
        CLUSTER_TIMEZONE_AFRICA_WINDHOEK,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_ADAK")]
        CLUSTER_TIMEZONE_AMERICA_ADAK,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_ANCHORAGE")]
        CLUSTER_TIMEZONE_AMERICA_ANCHORAGE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_ARAGUAINA")]
        CLUSTER_TIMEZONE_AMERICA_ARAGUAINA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_ARGENTINA_BUENOS_AIRES")]
        CLUSTER_TIMEZONE_AMERICA_ARGENTINA_BUENOS_AIRES,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_ARGENTINA_CATAMARCA")]
        CLUSTER_TIMEZONE_AMERICA_ARGENTINA_CATAMARCA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_ARGENTINA_CORDOBA")]
        CLUSTER_TIMEZONE_AMERICA_ARGENTINA_CORDOBA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_ARGENTINA_JUJUY")]
        CLUSTER_TIMEZONE_AMERICA_ARGENTINA_JUJUY,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_ARGENTINA_LA_RIOJA")]
        CLUSTER_TIMEZONE_AMERICA_ARGENTINA_LA_RIOJA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_ARGENTINA_MENDOZA")]
        CLUSTER_TIMEZONE_AMERICA_ARGENTINA_MENDOZA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_ARGENTINA_RIO_GALLEGOS")]
        CLUSTER_TIMEZONE_AMERICA_ARGENTINA_RIO_GALLEGOS,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_ARGENTINA_SALTA")]
        CLUSTER_TIMEZONE_AMERICA_ARGENTINA_SALTA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_ARGENTINA_SAN_JUAN")]
        CLUSTER_TIMEZONE_AMERICA_ARGENTINA_SAN_JUAN,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_ARGENTINA_SAN_LUIS")]
        CLUSTER_TIMEZONE_AMERICA_ARGENTINA_SAN_LUIS,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_ARGENTINA_TUCUMAN")]
        CLUSTER_TIMEZONE_AMERICA_ARGENTINA_TUCUMAN,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_ARGENTINA_USHUAIA")]
        CLUSTER_TIMEZONE_AMERICA_ARGENTINA_USHUAIA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_ATIKOKAN")]
        CLUSTER_TIMEZONE_AMERICA_ATIKOKAN,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_BAHIA")]
        CLUSTER_TIMEZONE_AMERICA_BAHIA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_BARBADOS")]
        CLUSTER_TIMEZONE_AMERICA_BARBADOS,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_BELEM")]
        CLUSTER_TIMEZONE_AMERICA_BELEM,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_BELIZE")]
        CLUSTER_TIMEZONE_AMERICA_BELIZE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_BOA_VISTA")]
        CLUSTER_TIMEZONE_AMERICA_BOA_VISTA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_BOGOTA")]
        CLUSTER_TIMEZONE_AMERICA_BOGOTA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_BOISE")]
        CLUSTER_TIMEZONE_AMERICA_BOISE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_CAMBRIDGE_BAY")]
        CLUSTER_TIMEZONE_AMERICA_CAMBRIDGE_BAY,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_CAMPO_GRANDE")]
        CLUSTER_TIMEZONE_AMERICA_CAMPO_GRANDE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_CANCUN")]
        CLUSTER_TIMEZONE_AMERICA_CANCUN,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_CARACAS")]
        CLUSTER_TIMEZONE_AMERICA_CARACAS,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_CAYENNE")]
        CLUSTER_TIMEZONE_AMERICA_CAYENNE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_CHICAGO")]
        CLUSTER_TIMEZONE_AMERICA_CHICAGO,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_CHIHUAHUA")]
        CLUSTER_TIMEZONE_AMERICA_CHIHUAHUA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_CIUDAD_JUAREZ")]
        CLUSTER_TIMEZONE_AMERICA_CIUDAD_JUAREZ,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_COSTA_RICA")]
        CLUSTER_TIMEZONE_AMERICA_COSTA_RICA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_CUIABA")]
        CLUSTER_TIMEZONE_AMERICA_CUIABA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_DANMARKSHAVN")]
        CLUSTER_TIMEZONE_AMERICA_DANMARKSHAVN,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_DAWSON")]
        CLUSTER_TIMEZONE_AMERICA_DAWSON,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_DAWSON_CREEK")]
        CLUSTER_TIMEZONE_AMERICA_DAWSON_CREEK,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_DENVER")]
        CLUSTER_TIMEZONE_AMERICA_DENVER,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_DETROIT")]
        CLUSTER_TIMEZONE_AMERICA_DETROIT,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_EDMONTON")]
        CLUSTER_TIMEZONE_AMERICA_EDMONTON,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_EIRUNEPE")]
        CLUSTER_TIMEZONE_AMERICA_EIRUNEPE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_EL_SALVADOR")]
        CLUSTER_TIMEZONE_AMERICA_EL_SALVADOR,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_FORTALEZA")]
        CLUSTER_TIMEZONE_AMERICA_FORTALEZA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_FORT_NELSON")]
        CLUSTER_TIMEZONE_AMERICA_FORT_NELSON,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_GLACE_BAY")]
        CLUSTER_TIMEZONE_AMERICA_GLACE_BAY,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_GOOSE_BAY")]
        CLUSTER_TIMEZONE_AMERICA_GOOSE_BAY,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_GRAND_TURK")]
        CLUSTER_TIMEZONE_AMERICA_GRAND_TURK,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_GUATEMALA")]
        CLUSTER_TIMEZONE_AMERICA_GUATEMALA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_GUAYAQUIL")]
        CLUSTER_TIMEZONE_AMERICA_GUAYAQUIL,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_GUYANA")]
        CLUSTER_TIMEZONE_AMERICA_GUYANA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_HALIFAX")]
        CLUSTER_TIMEZONE_AMERICA_HALIFAX,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_HAVANA")]
        CLUSTER_TIMEZONE_AMERICA_HAVANA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_INDIANA_INDIANAPOLIS")]
        CLUSTER_TIMEZONE_AMERICA_INDIANA_INDIANAPOLIS,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_INDIANA_KNOX")]
        CLUSTER_TIMEZONE_AMERICA_INDIANA_KNOX,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_INDIANA_MARENGO")]
        CLUSTER_TIMEZONE_AMERICA_INDIANA_MARENGO,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_INDIANA_PETERSBURG")]
        CLUSTER_TIMEZONE_AMERICA_INDIANA_PETERSBURG,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_INDIANA_TELL_CITY")]
        CLUSTER_TIMEZONE_AMERICA_INDIANA_TELL_CITY,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_INDIANA_VEVAY")]
        CLUSTER_TIMEZONE_AMERICA_INDIANA_VEVAY,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_INDIANA_VINCENNES")]
        CLUSTER_TIMEZONE_AMERICA_INDIANA_VINCENNES,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_INDIANA_WINAMAC")]
        CLUSTER_TIMEZONE_AMERICA_INDIANA_WINAMAC,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_INUVIK")]
        CLUSTER_TIMEZONE_AMERICA_INUVIK,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_IQALUIT")]
        CLUSTER_TIMEZONE_AMERICA_IQALUIT,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_JAMAICA")]
        CLUSTER_TIMEZONE_AMERICA_JAMAICA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_JUNEAU")]
        CLUSTER_TIMEZONE_AMERICA_JUNEAU,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_KENTUCKY_LOUISVILLE")]
        CLUSTER_TIMEZONE_AMERICA_KENTUCKY_LOUISVILLE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_KENTUCKY_MONTICELLO")]
        CLUSTER_TIMEZONE_AMERICA_KENTUCKY_MONTICELLO,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_LA_PAZ")]
        CLUSTER_TIMEZONE_AMERICA_LA_PAZ,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_LIMA")]
        CLUSTER_TIMEZONE_AMERICA_LIMA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_LOS_ANGELES")]
        CLUSTER_TIMEZONE_AMERICA_LOS_ANGELES,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_MACEIO")]
        CLUSTER_TIMEZONE_AMERICA_MACEIO,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_MANAGUA")]
        CLUSTER_TIMEZONE_AMERICA_MANAGUA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_MANAUS")]
        CLUSTER_TIMEZONE_AMERICA_MANAUS,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_MARTINIQUE")]
        CLUSTER_TIMEZONE_AMERICA_MARTINIQUE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_MATAMOROS")]
        CLUSTER_TIMEZONE_AMERICA_MATAMOROS,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_MENOMINEE")]
        CLUSTER_TIMEZONE_AMERICA_MENOMINEE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_MERIDA")]
        CLUSTER_TIMEZONE_AMERICA_MERIDA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_METLAKATLA")]
        CLUSTER_TIMEZONE_AMERICA_METLAKATLA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_MEXICO_CITY")]
        CLUSTER_TIMEZONE_AMERICA_MEXICO_CITY,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_MIQUELON")]
        CLUSTER_TIMEZONE_AMERICA_MIQUELON,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_MONCTON")]
        CLUSTER_TIMEZONE_AMERICA_MONCTON,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_MONTERREY")]
        CLUSTER_TIMEZONE_AMERICA_MONTERREY,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_MONTEVIDEO")]
        CLUSTER_TIMEZONE_AMERICA_MONTEVIDEO,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_NEW_YORK")]
        CLUSTER_TIMEZONE_AMERICA_NEW_YORK,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_NOME")]
        CLUSTER_TIMEZONE_AMERICA_NOME,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_NORONHA")]
        CLUSTER_TIMEZONE_AMERICA_NORONHA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_NORTH_DAKOTA_BEULAH")]
        CLUSTER_TIMEZONE_AMERICA_NORTH_DAKOTA_BEULAH,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_NORTH_DAKOTA_CENTER")]
        CLUSTER_TIMEZONE_AMERICA_NORTH_DAKOTA_CENTER,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_NORTH_DAKOTA_NEW_SALEM")]
        CLUSTER_TIMEZONE_AMERICA_NORTH_DAKOTA_NEW_SALEM,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_OJINAGA")]
        CLUSTER_TIMEZONE_AMERICA_OJINAGA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_PANAMA")]
        CLUSTER_TIMEZONE_AMERICA_PANAMA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_PARAMARIBO")]
        CLUSTER_TIMEZONE_AMERICA_PARAMARIBO,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_PHOENIX")]
        CLUSTER_TIMEZONE_AMERICA_PHOENIX,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_PORTO_VELHO")]
        CLUSTER_TIMEZONE_AMERICA_PORTO_VELHO,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_PUERTO_RICO")]
        CLUSTER_TIMEZONE_AMERICA_PUERTO_RICO,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_PUNTA_ARENAS")]
        CLUSTER_TIMEZONE_AMERICA_PUNTA_ARENAS,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_RANKIN_INLET")]
        CLUSTER_TIMEZONE_AMERICA_RANKIN_INLET,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_RECIFE")]
        CLUSTER_TIMEZONE_AMERICA_RECIFE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_REGINA")]
        CLUSTER_TIMEZONE_AMERICA_REGINA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_RESOLUTE")]
        CLUSTER_TIMEZONE_AMERICA_RESOLUTE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_RIO_BRANCO")]
        CLUSTER_TIMEZONE_AMERICA_RIO_BRANCO,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_SANTAREM")]
        CLUSTER_TIMEZONE_AMERICA_SANTAREM,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_SANTIAGO")]
        CLUSTER_TIMEZONE_AMERICA_SANTIAGO,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_SAO_PAULO")]
        CLUSTER_TIMEZONE_AMERICA_SAO_PAULO,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_SCORESBYSUND")]
        CLUSTER_TIMEZONE_AMERICA_SCORESBYSUND,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_SITKA")]
        CLUSTER_TIMEZONE_AMERICA_SITKA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_ST_JOHNS")]
        CLUSTER_TIMEZONE_AMERICA_ST_JOHNS,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_SWIFT_CURRENT")]
        CLUSTER_TIMEZONE_AMERICA_SWIFT_CURRENT,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_TEGUCIGALPA")]
        CLUSTER_TIMEZONE_AMERICA_TEGUCIGALPA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_THULE")]
        CLUSTER_TIMEZONE_AMERICA_THULE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_TIJUANA")]
        CLUSTER_TIMEZONE_AMERICA_TIJUANA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_TORONTO")]
        CLUSTER_TIMEZONE_AMERICA_TORONTO,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_VANCOUVER")]
        CLUSTER_TIMEZONE_AMERICA_VANCOUVER,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_WHITEHORSE")]
        CLUSTER_TIMEZONE_AMERICA_WHITEHORSE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_WINNIPEG")]
        CLUSTER_TIMEZONE_AMERICA_WINNIPEG,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_YAKUTAT")]
        CLUSTER_TIMEZONE_AMERICA_YAKUTAT,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ANTARCTICA_CASEY")]
        CLUSTER_TIMEZONE_ANTARCTICA_CASEY,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ANTARCTICA_DAVIS")]
        CLUSTER_TIMEZONE_ANTARCTICA_DAVIS,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ANTARCTICA_MACQUARIE")]
        CLUSTER_TIMEZONE_ANTARCTICA_MACQUARIE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ANTARCTICA_MAWSON")]
        CLUSTER_TIMEZONE_ANTARCTICA_MAWSON,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ANTARCTICA_PALMER")]
        CLUSTER_TIMEZONE_ANTARCTICA_PALMER,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ANTARCTICA_ROTHERA")]
        CLUSTER_TIMEZONE_ANTARCTICA_ROTHERA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ANTARCTICA_TROLL")]
        CLUSTER_TIMEZONE_ANTARCTICA_TROLL,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_ALMATY")]
        CLUSTER_TIMEZONE_ASIA_ALMATY,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_ANADYR")]
        CLUSTER_TIMEZONE_ASIA_ANADYR,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_AQTAU")]
        CLUSTER_TIMEZONE_ASIA_AQTAU,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_AQTOBE")]
        CLUSTER_TIMEZONE_ASIA_AQTOBE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_ASHGABAT")]
        CLUSTER_TIMEZONE_ASIA_ASHGABAT,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_ATYRAU")]
        CLUSTER_TIMEZONE_ASIA_ATYRAU,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_BAGHDAD")]
        CLUSTER_TIMEZONE_ASIA_BAGHDAD,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_BAKU")]
        CLUSTER_TIMEZONE_ASIA_BAKU,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_BANGKOK")]
        CLUSTER_TIMEZONE_ASIA_BANGKOK,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_BARNAUL")]
        CLUSTER_TIMEZONE_ASIA_BARNAUL,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_BISHKEK")]
        CLUSTER_TIMEZONE_ASIA_BISHKEK,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_CHITA")]
        CLUSTER_TIMEZONE_ASIA_CHITA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_CHOIBALSAN")]
        CLUSTER_TIMEZONE_ASIA_CHOIBALSAN,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_COLOMBO")]
        CLUSTER_TIMEZONE_ASIA_COLOMBO,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_DAMASCUS")]
        CLUSTER_TIMEZONE_ASIA_DAMASCUS,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_DHAKA")]
        CLUSTER_TIMEZONE_ASIA_DHAKA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_DILI")]
        CLUSTER_TIMEZONE_ASIA_DILI,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_DUBAI")]
        CLUSTER_TIMEZONE_ASIA_DUBAI,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_DUSHANBE")]
        CLUSTER_TIMEZONE_ASIA_DUSHANBE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_FAMAGUSTA")]
        CLUSTER_TIMEZONE_ASIA_FAMAGUSTA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_HONG_KONG")]
        CLUSTER_TIMEZONE_ASIA_HONG_KONG,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_HOVD")]
        CLUSTER_TIMEZONE_ASIA_HOVD,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_HO_CHI_MINH")]
        CLUSTER_TIMEZONE_ASIA_HO_CHI_MINH,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_IRKUTSK")]
        CLUSTER_TIMEZONE_ASIA_IRKUTSK,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_JAKARTA")]
        CLUSTER_TIMEZONE_ASIA_JAKARTA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_JAYAPURA")]
        CLUSTER_TIMEZONE_ASIA_JAYAPURA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_JERUSALEM")]
        CLUSTER_TIMEZONE_ASIA_JERUSALEM,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_KABUL")]
        CLUSTER_TIMEZONE_ASIA_KABUL,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_KAMCHATKA")]
        CLUSTER_TIMEZONE_ASIA_KAMCHATKA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_KARACHI")]
        CLUSTER_TIMEZONE_ASIA_KARACHI,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_KATHMANDU")]
        CLUSTER_TIMEZONE_ASIA_KATHMANDU,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_KHANDYGA")]
        CLUSTER_TIMEZONE_ASIA_KHANDYGA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_KOLKATA")]
        CLUSTER_TIMEZONE_ASIA_KOLKATA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_KRASNOYARSK")]
        CLUSTER_TIMEZONE_ASIA_KRASNOYARSK,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_KUCHING")]
        CLUSTER_TIMEZONE_ASIA_KUCHING,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_MACAU")]
        CLUSTER_TIMEZONE_ASIA_MACAU,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_MAGADAN")]
        CLUSTER_TIMEZONE_ASIA_MAGADAN,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_MAKASSAR")]
        CLUSTER_TIMEZONE_ASIA_MAKASSAR,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_MANILA")]
        CLUSTER_TIMEZONE_ASIA_MANILA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_NICOSIA")]
        CLUSTER_TIMEZONE_ASIA_NICOSIA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_NOVOKUZNETSK")]
        CLUSTER_TIMEZONE_ASIA_NOVOKUZNETSK,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_NOVOSIBIRSK")]
        CLUSTER_TIMEZONE_ASIA_NOVOSIBIRSK,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_OMSK")]
        CLUSTER_TIMEZONE_ASIA_OMSK,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_ORAL")]
        CLUSTER_TIMEZONE_ASIA_ORAL,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_PONTIANAK")]
        CLUSTER_TIMEZONE_ASIA_PONTIANAK,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_PYONGYANG")]
        CLUSTER_TIMEZONE_ASIA_PYONGYANG,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_QATAR")]
        CLUSTER_TIMEZONE_ASIA_QATAR,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_QOSTANAY")]
        CLUSTER_TIMEZONE_ASIA_QOSTANAY,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_QYZYLORDA")]
        CLUSTER_TIMEZONE_ASIA_QYZYLORDA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_RIYADH")]
        CLUSTER_TIMEZONE_ASIA_RIYADH,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_SAKHALIN")]
        CLUSTER_TIMEZONE_ASIA_SAKHALIN,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_SAMARKAND")]
        CLUSTER_TIMEZONE_ASIA_SAMARKAND,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_SEOUL")]
        CLUSTER_TIMEZONE_ASIA_SEOUL,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_SHANGHAI")]
        CLUSTER_TIMEZONE_ASIA_SHANGHAI,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_SINGAPORE")]
        CLUSTER_TIMEZONE_ASIA_SINGAPORE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_SREDNEKOLYMSK")]
        CLUSTER_TIMEZONE_ASIA_SREDNEKOLYMSK,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_TAIPEI")]
        CLUSTER_TIMEZONE_ASIA_TAIPEI,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_TASHKENT")]
        CLUSTER_TIMEZONE_ASIA_TASHKENT,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_TBILISI")]
        CLUSTER_TIMEZONE_ASIA_TBILISI,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_TEHRAN")]
        CLUSTER_TIMEZONE_ASIA_TEHRAN,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_THIMPHU")]
        CLUSTER_TIMEZONE_ASIA_THIMPHU,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_TOKYO")]
        CLUSTER_TIMEZONE_ASIA_TOKYO,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_TOMSK")]
        CLUSTER_TIMEZONE_ASIA_TOMSK,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_ULAANBAATAR")]
        CLUSTER_TIMEZONE_ASIA_ULAANBAATAR,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_URUMQI")]
        CLUSTER_TIMEZONE_ASIA_URUMQI,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_VLADIVOSTOK")]
        CLUSTER_TIMEZONE_ASIA_VLADIVOSTOK,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_YAKUTSK")]
        CLUSTER_TIMEZONE_ASIA_YAKUTSK,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_YANGON")]
        CLUSTER_TIMEZONE_ASIA_YANGON,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_YEKATERINBURG")]
        CLUSTER_TIMEZONE_ASIA_YEKATERINBURG,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_YEREVAN")]
        CLUSTER_TIMEZONE_ASIA_YEREVAN,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ATLANTIC_AZORES")]
        CLUSTER_TIMEZONE_ATLANTIC_AZORES,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ATLANTIC_BERMUDA")]
        CLUSTER_TIMEZONE_ATLANTIC_BERMUDA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ATLANTIC_CANARY")]
        CLUSTER_TIMEZONE_ATLANTIC_CANARY,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ATLANTIC_CAPE_VERDE")]
        CLUSTER_TIMEZONE_ATLANTIC_CAPE_VERDE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ATLANTIC_FAROE")]
        CLUSTER_TIMEZONE_ATLANTIC_FAROE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ATLANTIC_MADEIRA")]
        CLUSTER_TIMEZONE_ATLANTIC_MADEIRA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ATLANTIC_SOUTH_GEORGIA")]
        CLUSTER_TIMEZONE_ATLANTIC_SOUTH_GEORGIA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ATLANTIC_STANLEY")]
        CLUSTER_TIMEZONE_ATLANTIC_STANLEY,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AUSTRALIA_ADELAIDE")]
        CLUSTER_TIMEZONE_AUSTRALIA_ADELAIDE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AUSTRALIA_BRISBANE")]
        CLUSTER_TIMEZONE_AUSTRALIA_BRISBANE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AUSTRALIA_BROKEN_HILL")]
        CLUSTER_TIMEZONE_AUSTRALIA_BROKEN_HILL,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AUSTRALIA_DARWIN")]
        CLUSTER_TIMEZONE_AUSTRALIA_DARWIN,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AUSTRALIA_EUCLA")]
        CLUSTER_TIMEZONE_AUSTRALIA_EUCLA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AUSTRALIA_HOBART")]
        CLUSTER_TIMEZONE_AUSTRALIA_HOBART,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AUSTRALIA_LINDEMAN")]
        CLUSTER_TIMEZONE_AUSTRALIA_LINDEMAN,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AUSTRALIA_LORD_HOWE")]
        CLUSTER_TIMEZONE_AUSTRALIA_LORD_HOWE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AUSTRALIA_MELBOURNE")]
        CLUSTER_TIMEZONE_AUSTRALIA_MELBOURNE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AUSTRALIA_PERTH")]
        CLUSTER_TIMEZONE_AUSTRALIA_PERTH,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AUSTRALIA_SYDNEY")]
        CLUSTER_TIMEZONE_AUSTRALIA_SYDNEY,

        [EnumMember(Value = "CLUSTER_TIMEZONE_CET")]
        CLUSTER_TIMEZONE_CET,

        [EnumMember(Value = "CLUSTER_TIMEZONE_CST6CDT")]
        CLUSTER_TIMEZONE_CST6CDT,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EET")]
        CLUSTER_TIMEZONE_EET,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EST5EDT")]
        CLUSTER_TIMEZONE_EST5EDT,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_AMSTERDAM")]
        CLUSTER_TIMEZONE_EUROPE_AMSTERDAM,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_ANDORRA")]
        CLUSTER_TIMEZONE_EUROPE_ANDORRA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_ASTRAKHAN")]
        CLUSTER_TIMEZONE_EUROPE_ASTRAKHAN,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_ATHENS")]
        CLUSTER_TIMEZONE_EUROPE_ATHENS,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_BELGRADE")]
        CLUSTER_TIMEZONE_EUROPE_BELGRADE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_BERLIN")]
        CLUSTER_TIMEZONE_EUROPE_BERLIN,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_BRUSSELS")]
        CLUSTER_TIMEZONE_EUROPE_BRUSSELS,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_BUCHAREST")]
        CLUSTER_TIMEZONE_EUROPE_BUCHAREST,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_BUDAPEST")]
        CLUSTER_TIMEZONE_EUROPE_BUDAPEST,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_CHISINAU")]
        CLUSTER_TIMEZONE_EUROPE_CHISINAU,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_DUBLIN")]
        CLUSTER_TIMEZONE_EUROPE_DUBLIN,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_GIBRALTAR")]
        CLUSTER_TIMEZONE_EUROPE_GIBRALTAR,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_HELSINKI")]
        CLUSTER_TIMEZONE_EUROPE_HELSINKI,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_ISTANBUL")]
        CLUSTER_TIMEZONE_EUROPE_ISTANBUL,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_KALININGRAD")]
        CLUSTER_TIMEZONE_EUROPE_KALININGRAD,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_KIROV")]
        CLUSTER_TIMEZONE_EUROPE_KIROV,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_KYIV")]
        CLUSTER_TIMEZONE_EUROPE_KYIV,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_LISBON")]
        CLUSTER_TIMEZONE_EUROPE_LISBON,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_LONDON")]
        CLUSTER_TIMEZONE_EUROPE_LONDON,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_MADRID")]
        CLUSTER_TIMEZONE_EUROPE_MADRID,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_MALTA")]
        CLUSTER_TIMEZONE_EUROPE_MALTA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_MINSK")]
        CLUSTER_TIMEZONE_EUROPE_MINSK,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_MOSCOW")]
        CLUSTER_TIMEZONE_EUROPE_MOSCOW,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_PARIS")]
        CLUSTER_TIMEZONE_EUROPE_PARIS,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_PRAGUE")]
        CLUSTER_TIMEZONE_EUROPE_PRAGUE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_RIGA")]
        CLUSTER_TIMEZONE_EUROPE_RIGA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_ROME")]
        CLUSTER_TIMEZONE_EUROPE_ROME,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_SAMARA")]
        CLUSTER_TIMEZONE_EUROPE_SAMARA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_SARATOV")]
        CLUSTER_TIMEZONE_EUROPE_SARATOV,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_SIMFEROPOL")]
        CLUSTER_TIMEZONE_EUROPE_SIMFEROPOL,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_SOFIA")]
        CLUSTER_TIMEZONE_EUROPE_SOFIA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_TALLINN")]
        CLUSTER_TIMEZONE_EUROPE_TALLINN,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_TIRANE")]
        CLUSTER_TIMEZONE_EUROPE_TIRANE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_ULYANOVSK")]
        CLUSTER_TIMEZONE_EUROPE_ULYANOVSK,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_VIENNA")]
        CLUSTER_TIMEZONE_EUROPE_VIENNA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_VILNIUS")]
        CLUSTER_TIMEZONE_EUROPE_VILNIUS,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_VOLGOGRAD")]
        CLUSTER_TIMEZONE_EUROPE_VOLGOGRAD,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_WARSAW")]
        CLUSTER_TIMEZONE_EUROPE_WARSAW,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_ZURICH")]
        CLUSTER_TIMEZONE_EUROPE_ZURICH,

        [EnumMember(Value = "CLUSTER_TIMEZONE_INDIAN_CHAGOS")]
        CLUSTER_TIMEZONE_INDIAN_CHAGOS,

        [EnumMember(Value = "CLUSTER_TIMEZONE_INDIAN_MALDIVES")]
        CLUSTER_TIMEZONE_INDIAN_MALDIVES,

        [EnumMember(Value = "CLUSTER_TIMEZONE_INDIAN_MAURITIUS")]
        CLUSTER_TIMEZONE_INDIAN_MAURITIUS,

        [EnumMember(Value = "CLUSTER_TIMEZONE_MET")]
        CLUSTER_TIMEZONE_MET,

        [EnumMember(Value = "CLUSTER_TIMEZONE_MST7MDT")]
        CLUSTER_TIMEZONE_MST7MDT,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_APIA")]
        CLUSTER_TIMEZONE_PACIFIC_APIA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_AUCKLAND")]
        CLUSTER_TIMEZONE_PACIFIC_AUCKLAND,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_BOUGAINVILLE")]
        CLUSTER_TIMEZONE_PACIFIC_BOUGAINVILLE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_CHATHAM")]
        CLUSTER_TIMEZONE_PACIFIC_CHATHAM,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_EASTER")]
        CLUSTER_TIMEZONE_PACIFIC_EASTER,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_EFATE")]
        CLUSTER_TIMEZONE_PACIFIC_EFATE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_FAKAOFO")]
        CLUSTER_TIMEZONE_PACIFIC_FAKAOFO,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_FIJI")]
        CLUSTER_TIMEZONE_PACIFIC_FIJI,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_GALAPAGOS")]
        CLUSTER_TIMEZONE_PACIFIC_GALAPAGOS,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_GAMBIER")]
        CLUSTER_TIMEZONE_PACIFIC_GAMBIER,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_GUADALCANAL")]
        CLUSTER_TIMEZONE_PACIFIC_GUADALCANAL,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_GUAM")]
        CLUSTER_TIMEZONE_PACIFIC_GUAM,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_HONOLULU")]
        CLUSTER_TIMEZONE_PACIFIC_HONOLULU,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_KANTON")]
        CLUSTER_TIMEZONE_PACIFIC_KANTON,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_KIRITIMATI")]
        CLUSTER_TIMEZONE_PACIFIC_KIRITIMATI,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_KOSRAE")]
        CLUSTER_TIMEZONE_PACIFIC_KOSRAE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_KWAJALEIN")]
        CLUSTER_TIMEZONE_PACIFIC_KWAJALEIN,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_MARQUESAS")]
        CLUSTER_TIMEZONE_PACIFIC_MARQUESAS,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_MIDWAY")]
        CLUSTER_TIMEZONE_PACIFIC_MIDWAY,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_NAURU")]
        CLUSTER_TIMEZONE_PACIFIC_NAURU,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_NIUE")]
        CLUSTER_TIMEZONE_PACIFIC_NIUE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_NORFOLK")]
        CLUSTER_TIMEZONE_PACIFIC_NORFOLK,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_NOUMEA")]
        CLUSTER_TIMEZONE_PACIFIC_NOUMEA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_PAGO_PAGO")]
        CLUSTER_TIMEZONE_PACIFIC_PAGO_PAGO,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_PALAU")]
        CLUSTER_TIMEZONE_PACIFIC_PALAU,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_PITCAIRN")]
        CLUSTER_TIMEZONE_PACIFIC_PITCAIRN,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_PORT_MORESBY")]
        CLUSTER_TIMEZONE_PACIFIC_PORT_MORESBY,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_RAROTONGA")]
        CLUSTER_TIMEZONE_PACIFIC_RAROTONGA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_TAHITI")]
        CLUSTER_TIMEZONE_PACIFIC_TAHITI,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_TARAWA")]
        CLUSTER_TIMEZONE_PACIFIC_TARAWA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_TONGATAPU")]
        CLUSTER_TIMEZONE_PACIFIC_TONGATAPU,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PST8PDT")]
        CLUSTER_TIMEZONE_PST8PDT,

        [EnumMember(Value = "CLUSTER_TIMEZONE_UNSPECIFIED")]
        CLUSTER_TIMEZONE_UNSPECIFIED,

        [EnumMember(Value = "CLUSTER_TIMEZONE_UTC")]
        CLUSTER_TIMEZONE_UTC,

        [EnumMember(Value = "CLUSTER_TIMEZONE_WET")]
        CLUSTER_TIMEZONE_WET,

        [EnumMember(Value = "UNKNOWN")]
        UNKNOWN


    } // enum ClusterTimezoneType

} // namespace RubrikSecurityCloud.Types