// ClusterTimezoneType.cs
//
// This generated file is part of the Rubrik PowerShell SDK.
// Manual changes to this file may be lost.

#nullable enable
using System;
using System.Collections.Generic;
using System.Text;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Rubrik.SecurityCloud.Types
{
    public enum ClusterTimezoneType
    {
        [EnumMember(Value = "CLUSTER_TIMEZONE_AFRICA_JOHANNESBURG")]
        CLUSTER_TIMEZONE_AFRICA_JOHANNESBURG,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AFRICA_LAGOS")]
        CLUSTER_TIMEZONE_AFRICA_LAGOS,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AFRICA_NAIROBI")]
        CLUSTER_TIMEZONE_AFRICA_NAIROBI,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_ANCHORAGE")]
        CLUSTER_TIMEZONE_AMERICA_ANCHORAGE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_ARAGUAINA")]
        CLUSTER_TIMEZONE_AMERICA_ARAGUAINA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_ATIKOKAN")]
        CLUSTER_TIMEZONE_AMERICA_ATIKOKAN,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_BARBADOS")]
        CLUSTER_TIMEZONE_AMERICA_BARBADOS,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_BOGOTA")]
        CLUSTER_TIMEZONE_AMERICA_BOGOTA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_CHICAGO")]
        CLUSTER_TIMEZONE_AMERICA_CHICAGO,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_COSTA_RICA")]
        CLUSTER_TIMEZONE_AMERICA_COSTA_RICA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_DENVER")]
        CLUSTER_TIMEZONE_AMERICA_DENVER,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_LOS_ANGELES")]
        CLUSTER_TIMEZONE_AMERICA_LOS_ANGELES,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_MEXICO_CITY")]
        CLUSTER_TIMEZONE_AMERICA_MEXICO_CITY,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_NEW_YORK")]
        CLUSTER_TIMEZONE_AMERICA_NEW_YORK,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_NORONHA")]
        CLUSTER_TIMEZONE_AMERICA_NORONHA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_PANAMA")]
        CLUSTER_TIMEZONE_AMERICA_PANAMA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_PHOENIX")]
        CLUSTER_TIMEZONE_AMERICA_PHOENIX,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_SANTIAGO")]
        CLUSTER_TIMEZONE_AMERICA_SANTIAGO,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_ST_JOHNS")]
        CLUSTER_TIMEZONE_AMERICA_ST_JOHNS,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_TORONTO")]
        CLUSTER_TIMEZONE_AMERICA_TORONTO,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AMERICA_VANCOUVER")]
        CLUSTER_TIMEZONE_AMERICA_VANCOUVER,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_BANGKOK")]
        CLUSTER_TIMEZONE_ASIA_BANGKOK,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_DHAKA")]
        CLUSTER_TIMEZONE_ASIA_DHAKA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_DUBAI")]
        CLUSTER_TIMEZONE_ASIA_DUBAI,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_HONG_KONG")]
        CLUSTER_TIMEZONE_ASIA_HONG_KONG,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_KARACHI")]
        CLUSTER_TIMEZONE_ASIA_KARACHI,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_KATHMANDU")]
        CLUSTER_TIMEZONE_ASIA_KATHMANDU,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_KOLKATA")]
        CLUSTER_TIMEZONE_ASIA_KOLKATA,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_MAGADAN")]
        CLUSTER_TIMEZONE_ASIA_MAGADAN,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_SINGAPORE")]
        CLUSTER_TIMEZONE_ASIA_SINGAPORE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ASIA_TOKYO")]
        CLUSTER_TIMEZONE_ASIA_TOKYO,

        [EnumMember(Value = "CLUSTER_TIMEZONE_ATLANTIC_CAPE_VERDE")]
        CLUSTER_TIMEZONE_ATLANTIC_CAPE_VERDE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AUSTRALIA_ADELAIDE")]
        CLUSTER_TIMEZONE_AUSTRALIA_ADELAIDE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AUSTRALIA_BRISBANE")]
        CLUSTER_TIMEZONE_AUSTRALIA_BRISBANE,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AUSTRALIA_PERTH")]
        CLUSTER_TIMEZONE_AUSTRALIA_PERTH,

        [EnumMember(Value = "CLUSTER_TIMEZONE_AUSTRALIA_SYDNEY")]
        CLUSTER_TIMEZONE_AUSTRALIA_SYDNEY,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_AMSTERDAM")]
        CLUSTER_TIMEZONE_EUROPE_AMSTERDAM,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_ATHENS")]
        CLUSTER_TIMEZONE_EUROPE_ATHENS,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_LONDON")]
        CLUSTER_TIMEZONE_EUROPE_LONDON,

        [EnumMember(Value = "CLUSTER_TIMEZONE_EUROPE_MOSCOW")]
        CLUSTER_TIMEZONE_EUROPE_MOSCOW,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_AUCKLAND")]
        CLUSTER_TIMEZONE_PACIFIC_AUCKLAND,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_HONOLULU")]
        CLUSTER_TIMEZONE_PACIFIC_HONOLULU,

        [EnumMember(Value = "CLUSTER_TIMEZONE_PACIFIC_MIDWAY")]
        CLUSTER_TIMEZONE_PACIFIC_MIDWAY,

        [EnumMember(Value = "CLUSTER_TIMEZONE_UNSPECIFIED")]
        CLUSTER_TIMEZONE_UNSPECIFIED,

        [EnumMember(Value = "CLUSTER_TIMEZONE_UTC")]
        CLUSTER_TIMEZONE_UTC


    } // enum ClusterTimezoneType

} // namespace Rubrik.SecurityCloud.Types