// FilterType.cs
//
// This generated file is part of the Rubrik PowerShell SDK.
// Manual changes to this file may be lost.

#nullable enable
using System;
using System.Collections.Generic;
using System.Text;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace RubrikSecurityCloud.Types
{
    public enum FilterType
    {
        [EnumMember(Value = "UNKNOWN")]
        UNKNOWN,

        [EnumMember(Value = "FILTER_TYPE_UNSPECIFIED")]
        FILTER_TYPE_UNSPECIFIED,

        [EnumMember(Value = "SECURITY_DOCUMENT_DATA_CATEGORY")]
        SECURITY_DOCUMENT_DATA_CATEGORY,

        [EnumMember(Value = "SECURITY_DOCUMENT_DATA_TYPE")]
        SECURITY_DOCUMENT_DATA_TYPE,

        [EnumMember(Value = "SECURITY_DOCUMENT_DOCUMENT_TYPE")]
        SECURITY_DOCUMENT_DOCUMENT_TYPE,

        [EnumMember(Value = "SECURITY_DOCUMENT_EXPOSURE")]
        SECURITY_DOCUMENT_EXPOSURE,

        [EnumMember(Value = "SECURITY_DOCUMENT_HIT_COUNT")]
        SECURITY_DOCUMENT_HIT_COUNT,

        [EnumMember(Value = "SECURITY_DOCUMENT_LAST_ACCESS")]
        SECURITY_DOCUMENT_LAST_ACCESS,

        [EnumMember(Value = "SECURITY_DOCUMENT_LAST_MODIFIED")]
        SECURITY_DOCUMENT_LAST_MODIFIED,

        [EnumMember(Value = "SECURITY_DOCUMENT_MIP_LABEL")]
        SECURITY_DOCUMENT_MIP_LABEL,

        [EnumMember(Value = "SECURITY_DOCUMENT_SENSITIVITY")]
        SECURITY_DOCUMENT_SENSITIVITY,

        [EnumMember(Value = "SECURITY_IDENTITY_AES_ENCRYPTION_SUPPORTED")]
        SECURITY_IDENTITY_AES_ENCRYPTION_SUPPORTED,

        [EnumMember(Value = "SECURITY_IDENTITY_CAP_METADATA")]
        SECURITY_IDENTITY_CAP_METADATA,

        [EnumMember(Value = "SECURITY_IDENTITY_DEPARTMENT")]
        SECURITY_IDENTITY_DEPARTMENT,

        [EnumMember(Value = "SECURITY_IDENTITY_DESCENDANT_USERS_COUNT")]
        SECURITY_IDENTITY_DESCENDANT_USERS_COUNT,

        [EnumMember(Value = "SECURITY_IDENTITY_DES_ENCRYPTION_ENABLED")]
        SECURITY_IDENTITY_DES_ENCRYPTION_ENABLED,

        [EnumMember(Value = "SECURITY_IDENTITY_DIRECT_DESCENDANT_COUNT")]
        SECURITY_IDENTITY_DIRECT_DESCENDANT_COUNT,

        [EnumMember(Value = "SECURITY_IDENTITY_DOMAIN")]
        SECURITY_IDENTITY_DOMAIN,

        [EnumMember(Value = "SECURITY_IDENTITY_EVENT_ACTION_TYPE")]
        SECURITY_IDENTITY_EVENT_ACTION_TYPE,

        [EnumMember(Value = "SECURITY_IDENTITY_EVENT_ACTOR")]
        SECURITY_IDENTITY_EVENT_ACTOR,

        [EnumMember(Value = "SECURITY_IDENTITY_EVENT_CHANGED_ATTRIBUTE")]
        SECURITY_IDENTITY_EVENT_CHANGED_ATTRIBUTE,

        [EnumMember(Value = "SECURITY_IDENTITY_EVENT_CHANGED_ATT_NEW_VAL")]
        SECURITY_IDENTITY_EVENT_CHANGED_ATT_NEW_VAL,

        [EnumMember(Value = "SECURITY_IDENTITY_EVENT_CHANGED_ATT_OLD_VAL")]
        SECURITY_IDENTITY_EVENT_CHANGED_ATT_OLD_VAL,

        [EnumMember(Value = "SECURITY_IDENTITY_EVENT_DC_NAME")]
        SECURITY_IDENTITY_EVENT_DC_NAME,

        [EnumMember(Value = "SECURITY_IDENTITY_EVENT_SOURCE_ENTITY_ID")]
        SECURITY_IDENTITY_EVENT_SOURCE_ENTITY_ID,

        [EnumMember(Value = "SECURITY_IDENTITY_EVENT_TARGET_ENTITY")]
        SECURITY_IDENTITY_EVENT_TARGET_ENTITY,

        [EnumMember(Value = "SECURITY_IDENTITY_EVENT_TARGET_ENTITY_TYPE")]
        SECURITY_IDENTITY_EVENT_TARGET_ENTITY_TYPE,

        [EnumMember(Value = "SECURITY_IDENTITY_EVENT_TIMESTAMP")]
        SECURITY_IDENTITY_EVENT_TIMESTAMP,

        [EnumMember(Value = "SECURITY_IDENTITY_EVENT_TITLE")]
        SECURITY_IDENTITY_EVENT_TITLE,

        [EnumMember(Value = "SECURITY_IDENTITY_EVENT_TYPE")]
        SECURITY_IDENTITY_EVENT_TYPE,

        [EnumMember(Value = "SECURITY_IDENTITY_GROUP_MEMBERSHIP")]
        SECURITY_IDENTITY_GROUP_MEMBERSHIP,

        [EnumMember(Value = "SECURITY_IDENTITY_HAS_API_PERMISSIONS")]
        SECURITY_IDENTITY_HAS_API_PERMISSIONS,

        [EnumMember(Value = "SECURITY_IDENTITY_HAS_ROLES")]
        SECURITY_IDENTITY_HAS_ROLES,

        [EnumMember(Value = "SECURITY_IDENTITY_IDP_METADATA_LABEL")]
        SECURITY_IDENTITY_IDP_METADATA_LABEL,

        [EnumMember(Value = "SECURITY_IDENTITY_IDP_TYPE")]
        SECURITY_IDENTITY_IDP_TYPE,

        [EnumMember(Value = "SECURITY_IDENTITY_INSIGHT")]
        SECURITY_IDENTITY_INSIGHT,

        [EnumMember(Value = "SECURITY_IDENTITY_IS_DOMAIN_CONTROLLER")]
        SECURITY_IDENTITY_IS_DOMAIN_CONTROLLER,

        [EnumMember(Value = "SECURITY_IDENTITY_METADATA")]
        SECURITY_IDENTITY_METADATA,

        [EnumMember(Value = "SECURITY_IDENTITY_METADATA_BITMASK")]
        SECURITY_IDENTITY_METADATA_BITMASK,

        [EnumMember(Value = "SECURITY_IDENTITY_METADATA_LABEL")]
        SECURITY_IDENTITY_METADATA_LABEL,

        [EnumMember(Value = "SECURITY_IDENTITY_METADATA_LIST_LENGTH")]
        SECURITY_IDENTITY_METADATA_LIST_LENGTH,

        [EnumMember(Value = "SECURITY_IDENTITY_METADATA_VALUES")]
        SECURITY_IDENTITY_METADATA_VALUES,

        [EnumMember(Value = "SECURITY_IDENTITY_MFA_STRENGTH")]
        SECURITY_IDENTITY_MFA_STRENGTH,

        [EnumMember(Value = "SECURITY_IDENTITY_NAME")]
        SECURITY_IDENTITY_NAME,

        [EnumMember(Value = "SECURITY_IDENTITY_NATIVE_CREATION_TIME")]
        SECURITY_IDENTITY_NATIVE_CREATION_TIME,

        [EnumMember(Value = "SECURITY_IDENTITY_NUMBER_OF_SECRETS")]
        SECURITY_IDENTITY_NUMBER_OF_SECRETS,

        [EnumMember(Value = "SECURITY_IDENTITY_ORIGIN")]
        SECURITY_IDENTITY_ORIGIN,

        [EnumMember(Value = "SECURITY_IDENTITY_PASSWORD_NEVER_EXPIRES")]
        SECURITY_IDENTITY_PASSWORD_NEVER_EXPIRES,

        [EnumMember(Value = "SECURITY_IDENTITY_PASSWORD_NOT_REQUIRED")]
        SECURITY_IDENTITY_PASSWORD_NOT_REQUIRED,

        [EnumMember(Value = "SECURITY_IDENTITY_PASSWORD_REVERSIBLE_ENCRYPTION")]
        SECURITY_IDENTITY_PASSWORD_REVERSIBLE_ENCRYPTION,

        [EnumMember(Value = "SECURITY_IDENTITY_PRE_AUTH_NOT_ENABLED")]
        SECURITY_IDENTITY_PRE_AUTH_NOT_ENABLED,

        [EnumMember(Value = "SECURITY_IDENTITY_PRIVILEGE_TYPE")]
        SECURITY_IDENTITY_PRIVILEGE_TYPE,

        [EnumMember(Value = "SECURITY_IDENTITY_PWD_AGE")]
        SECURITY_IDENTITY_PWD_AGE,

        [EnumMember(Value = "SECURITY_IDENTITY_RC4_ENCRYPTION_SUPPORTED")]
        SECURITY_IDENTITY_RC4_ENCRYPTION_SUPPORTED,

        [EnumMember(Value = "SECURITY_IDENTITY_RESOURCE_BASED_CONSTRAINED_DELEGATION")]
        SECURITY_IDENTITY_RESOURCE_BASED_CONSTRAINED_DELEGATION,

        [EnumMember(Value = "SECURITY_IDENTITY_SECRET_CREATION_TIME")]
        SECURITY_IDENTITY_SECRET_CREATION_TIME,

        [EnumMember(Value = "SECURITY_IDENTITY_SECRET_EXPIRY_TIME")]
        SECURITY_IDENTITY_SECRET_EXPIRY_TIME,

        [EnumMember(Value = "SECURITY_IDENTITY_SENSITIVE_CANNOT_DELEGATE")]
        SECURITY_IDENTITY_SENSITIVE_CANNOT_DELEGATE,

        [EnumMember(Value = "SECURITY_IDENTITY_SERVICE_PRINCIPAL_NAME")]
        SECURITY_IDENTITY_SERVICE_PRINCIPAL_NAME,

        [EnumMember(Value = "SECURITY_IDENTITY_STATUS")]
        SECURITY_IDENTITY_STATUS,

        [EnumMember(Value = "SECURITY_IDENTITY_SYNCED_ONPREM_PRIVILEGED_ACCOUNT")]
        SECURITY_IDENTITY_SYNCED_ONPREM_PRIVILEGED_ACCOUNT,

        [EnumMember(Value = "SECURITY_IDENTITY_TITLE")]
        SECURITY_IDENTITY_TITLE,

        [EnumMember(Value = "SECURITY_IDENTITY_TYPE")]
        SECURITY_IDENTITY_TYPE,

        [EnumMember(Value = "SECURITY_IDENTITY_UNCONSTRAINED_DELEGATION")]
        SECURITY_IDENTITY_UNCONSTRAINED_DELEGATION,

        [EnumMember(Value = "SECURITY_IDENTITY_UNIQUE_IDENTIFIER")]
        SECURITY_IDENTITY_UNIQUE_IDENTIFIER,

        [EnumMember(Value = "SECURITY_IDP_ANONYMOUS_ACCESS_ENABLED")]
        SECURITY_IDP_ANONYMOUS_ACCESS_ENABLED,

        [EnumMember(Value = "SECURITY_IDP_CAP_METADATA")]
        SECURITY_IDP_CAP_METADATA,

        [EnumMember(Value = "SECURITY_IDP_CRITICAL_APP_COVERAGE")]
        SECURITY_IDP_CRITICAL_APP_COVERAGE,

        [EnumMember(Value = "SECURITY_IDP_DOMAIN")]
        SECURITY_IDP_DOMAIN,

        [EnumMember(Value = "SECURITY_IDP_HAS_GROUP_WITH_LABEL")]
        SECURITY_IDP_HAS_GROUP_WITH_LABEL,

        [EnumMember(Value = "SECURITY_IDP_HAS_USER_WITH_LABEL")]
        SECURITY_IDP_HAS_USER_WITH_LABEL,

        [EnumMember(Value = "SECURITY_IDP_INHERITANCE_ENABLED")]
        SECURITY_IDP_INHERITANCE_ENABLED,

        [EnumMember(Value = "SECURITY_IDP_METADATA_LABEL")]
        SECURITY_IDP_METADATA_LABEL,

        [EnumMember(Value = "SECURITY_IDP_METADATA_NUMERIC_COMPARISON")]
        SECURITY_IDP_METADATA_NUMERIC_COMPARISON,

        [EnumMember(Value = "SECURITY_IDP_METADATA_VALUE_LENGTH")]
        SECURITY_IDP_METADATA_VALUE_LENGTH,

        [EnumMember(Value = "SECURITY_IDP_PIM_APPROVAL_FOR_SENSITIVE_ROLES")]
        SECURITY_IDP_PIM_APPROVAL_FOR_SENSITIVE_ROLES,

        [EnumMember(Value = "SECURITY_IDP_PIM_MFA_FOR_PRIVILEGED_ROLES")]
        SECURITY_IDP_PIM_MFA_FOR_PRIVILEGED_ROLES,

        [EnumMember(Value = "SECURITY_IDP_PRIVILEGED_ACCOUNT_COUNT")]
        SECURITY_IDP_PRIVILEGED_ACCOUNT_COUNT,

        [EnumMember(Value = "SECURITY_IDP_PRIVILEGED_USER_COUNT")]
        SECURITY_IDP_PRIVILEGED_USER_COUNT,

        [EnumMember(Value = "SECURITY_IDP_SECURITY_DEFAULTS_ENABLED")]
        SECURITY_IDP_SECURITY_DEFAULTS_ENABLED,

        [EnumMember(Value = "SECURITY_IDP_TYPE")]
        SECURITY_IDP_TYPE,

        [EnumMember(Value = "SECURITY_IDP_WEAK_LOCKOUT_POLICY")]
        SECURITY_IDP_WEAK_LOCKOUT_POLICY,

        [EnumMember(Value = "SECURITY_IDP_WEAK_PASSWORD_POLICY")]
        SECURITY_IDP_WEAK_PASSWORD_POLICY,

        [EnumMember(Value = "SECURITY_SNAPPABLE_BACKUP")]
        SECURITY_SNAPPABLE_BACKUP,

        [EnumMember(Value = "SECURITY_SNAPPABLE_CLOUD_ACCOUNT")]
        SECURITY_SNAPPABLE_CLOUD_ACCOUNT,

        [EnumMember(Value = "SECURITY_SNAPPABLE_CREATED_AT")]
        SECURITY_SNAPPABLE_CREATED_AT,

        [EnumMember(Value = "SECURITY_SNAPPABLE_ENCRYPTION")]
        SECURITY_SNAPPABLE_ENCRYPTION,

        [EnumMember(Value = "SECURITY_SNAPPABLE_LOGGING")]
        SECURITY_SNAPPABLE_LOGGING,

        [EnumMember(Value = "SECURITY_SNAPPABLE_NAME")]
        SECURITY_SNAPPABLE_NAME,

        [EnumMember(Value = "SECURITY_SNAPPABLE_NETWORK_ACCESS")]
        SECURITY_SNAPPABLE_NETWORK_ACCESS,

        [EnumMember(Value = "SECURITY_SNAPPABLE_REGION")]
        SECURITY_SNAPPABLE_REGION,

        [EnumMember(Value = "SECURITY_SNAPPABLE_TAG")]
        SECURITY_SNAPPABLE_TAG,

        [EnumMember(Value = "SECURITY_SNAPPABLE_TYPE")]
        SECURITY_SNAPPABLE_TYPE


    } // enum FilterType

} // namespace RubrikSecurityCloud.Types