// IntuneDeviceManagementSecretSettingType.cs
//
// This generated file is part of the Rubrik PowerShell SDK.
// Manual changes to this file may be lost.

#nullable enable
using System;
using System.Collections.Generic;
using System.Text;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace RubrikSecurityCloud.Types
{
    public enum IntuneDeviceManagementSecretSettingType
    {
        [EnumMember(Value = "UNKNOWN")]
        UNKNOWN,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_AIRPLAY_PASSWORD")]
        INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_AIRPLAY_PASSWORD,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_ATP_OFFBOARDING")]
        INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_ATP_OFFBOARDING,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_ATP_ONBOARDING")]
        INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_ATP_ONBOARDING,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_ATP_ONBOARDING_FROM_CONNECTOR")]
        INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_ATP_ONBOARDING_FROM_CONNECTOR,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_AUTOLOGIN_PASSWORD")]
        INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_AUTOLOGIN_PASSWORD,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_CALDAV_PASSWORD")]
        INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_CALDAV_PASSWORD,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_CARDDAV_PASSWORD")]
        INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_CARDDAV_PASSWORD,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_CELLULAR_APN_PASSWORD")]
        INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_CELLULAR_APN_PASSWORD,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_CELLULAR_ATTACH_APN_PASSWORD")]
        INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_CELLULAR_ATTACH_APN_PASSWORD,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_DIRECTORY_SERVICE_PASSWORD")]
        INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_DIRECTORY_SERVICE_PASSWORD,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_FILEVAULT_PASSWORD")]
        INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_FILEVAULT_PASSWORD,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_HTTP_PROXY_PASSWORD")]
        INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_HTTP_PROXY_PASSWORD,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_LDAP_PASSWORD")]
        INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_LDAP_PASSWORD,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_NETWORK_PASSWORD")]
        INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_NETWORK_PASSWORD,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_PROFILE_IDENTIFICATION_PASSWORD")]
        INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_PROFILE_IDENTIFICATION_PASSWORD,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_PROFILE_REMOVAL_PASSWORD")]
        INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_PROFILE_REMOVAL_PASSWORD,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_SUBSCRIBED_CALENDAR_PASSWORD")]
        INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_SUBSCRIBED_CALENDAR_PASSWORD,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_UNKNOWN")]
        INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_UNKNOWN,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_WEB_CONTENT_FILTER_PASSWORD")]
        INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_WEB_CONTENT_FILTER_PASSWORD,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_XSAN_SHARED_SECRET")]
        INTUNE_DEVICE_MANAGEMENT_SECRET_SETTING_TYPE_XSAN_SHARED_SECRET


    } // enum IntuneDeviceManagementSecretSettingType

} // namespace RubrikSecurityCloud.Types