// IntuneDeviceManagementPolicyType.cs
//
// This generated file is part of the Rubrik PowerShell SDK.
// Manual changes to this file may be lost.

#nullable enable
using System;
using System.Collections.Generic;
using System.Text;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace RubrikSecurityCloud.Types
{
    public enum IntuneDeviceManagementPolicyType
    {
        [EnumMember(Value = "UNKNOWN")]
        UNKNOWN,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_ADMINISTRATIVE_TEMPLATES")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_ADMINISTRATIVE_TEMPLATES,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_ANDROID_FOR_WORK_MIGRATION_POLICY")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_ANDROID_FOR_WORK_MIGRATION_POLICY,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_BIOS_CONFIGURATIONS")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_BIOS_CONFIGURATIONS,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_BIOS_CONFIGURATIONS_REACT")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_BIOS_CONFIGURATIONS_REACT,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_CUSTOM")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_CUSTOM,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_CUSTOM_ADMINISTRATIVE_TEMPLATES")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_CUSTOM_ADMINISTRATIVE_TEMPLATES,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_DELIVERY_OPTIMIZATION")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_DELIVERY_OPTIMIZATION,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_DERIVED_CREDENTIAL")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_DERIVED_CREDENTIAL,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_DEVICE_FEATURES")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_DEVICE_FEATURES,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_DEVICE_FIRMWARE_CONFIGURATION_INTERFACE")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_DEVICE_FIRMWARE_CONFIGURATION_INTERFACE,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_DEVICE_FIRMWARE_CONFIGURATION_INTERFACE_REACT")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_DEVICE_FIRMWARE_CONFIGURATION_INTERFACE_REACT,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_DEVICE_RESTRICTIONS")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_DEVICE_RESTRICTIONS,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_DEVICE_RESTRICTIONS_WINDOWS_10_TEAM")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_DEVICE_RESTRICTIONS_WINDOWS_10_TEAM,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_DOMAIN_JOIN")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_DOMAIN_JOIN,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_EDITION_UPGRADE_AND_MODE_SWITCH")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_EDITION_UPGRADE_AND_MODE_SWITCH,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_EMAIL")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_EMAIL,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_EMAIL_SAMSUNG_KNOX_ONLY")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_EMAIL_SAMSUNG_KNOX_ONLY,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_ENDPOINT_PROTECTION")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_ENDPOINT_PROTECTION,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_ENDPOINT_SECURITY_ACB")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_ENDPOINT_SECURITY_ACB,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_ENDPOINT_SECURITY_ACCOUNT_PROTECTION")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_ENDPOINT_SECURITY_ACCOUNT_PROTECTION,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_ENDPOINT_SECURITY_ANTIVIRUS")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_ENDPOINT_SECURITY_ANTIVIRUS,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_ENDPOINT_SECURITY_ASR")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_ENDPOINT_SECURITY_ASR,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_ENDPOINT_SECURITY_DISK_ENCRYPTION")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_ENDPOINT_SECURITY_DISK_ENCRYPTION,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_ENDPOINT_SECURITY_EDR")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_ENDPOINT_SECURITY_EDR,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_ENDPOINT_SECURITY_EPM")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_ENDPOINT_SECURITY_EPM,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_ENDPOINT_SECURITY_FIREWALL")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_ENDPOINT_SECURITY_FIREWALL,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_EXTENSION")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_EXTENSION,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_IDENTITY_PROTECTION")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_IDENTITY_PROTECTION,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_KIOSK")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_KIOSK,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_MICROSOFT_DEFENDER_FOR_ENDPOINT")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_MICROSOFT_DEFENDER_FOR_ENDPOINT,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_MX_PROFILE_ZEBRA_ONLY")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_MX_PROFILE_ZEBRA_ONLY,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_NETWORK_BOUNDARY")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_NETWORK_BOUNDARY,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_OEM_CONFIG")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_OEM_CONFIG,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_OVERRIDE_GROUP_POLICY")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_OVERRIDE_GROUP_POLICY,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_PKCS_CERTIFICATE")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_PKCS_CERTIFICATE,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_PKCS_IMPORTED_CERTIFICATE")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_PKCS_IMPORTED_CERTIFICATE,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_PREFERENCE_FILE")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_PREFERENCE_FILE,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_PROPERTIES_CATALOG")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_PROPERTIES_CATALOG,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_SCEP_CERTIFICATE")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_SCEP_CERTIFICATE,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_SECURE_ASSESSMENT_EDUCATION")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_SECURE_ASSESSMENT_EDUCATION,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_SETTINGS_CATALOG")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_SETTINGS_CATALOG,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_SHARED_MULTI_USER_DEVICE")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_SHARED_MULTI_USER_DEVICE,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_SOFTWARE_UPDATES")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_SOFTWARE_UPDATES,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_TRUSTED_CERTIFICATE")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_TRUSTED_CERTIFICATE,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_UNKNOWN")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_UNKNOWN,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_VPN")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_VPN,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_WIFI")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_WIFI,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_WIFI_IMPORT")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_WIFI_IMPORT,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_WINDOWS_HEALTH_MONITORING")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_WINDOWS_HEALTH_MONITORING,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_WINDOWS_KIOSK")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_WINDOWS_KIOSK,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_WINDOWS_ZTDNS")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_WINDOWS_ZTDNS,

        [EnumMember(Value = "INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_WIRED_NETWORK")]
        INTUNE_DEVICE_MANAGEMENT_POLICY_TYPE_WIRED_NETWORK


    } // enum IntuneDeviceManagementPolicyType

} // namespace RubrikSecurityCloud.Types