// IntuneAppProtectionManagementType.cs
//
// This generated file is part of the Rubrik PowerShell SDK.
// Manual changes to this file may be lost.

#nullable enable
using System;
using System.Collections.Generic;
using System.Text;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace RubrikSecurityCloud.Types
{
    public enum IntuneAppProtectionManagementType
    {
        [EnumMember(Value = "UNKNOWN")]
        UNKNOWN,

        [EnumMember(Value = "INTUNE_APP_PROTECTION_MANAGEMENT_TYPE_ALL_APP_TYPES")]
        INTUNE_APP_PROTECTION_MANAGEMENT_TYPE_ALL_APP_TYPES,

        [EnumMember(Value = "INTUNE_APP_PROTECTION_MANAGEMENT_TYPE_ANDROID_ENTERPRISE")]
        INTUNE_APP_PROTECTION_MANAGEMENT_TYPE_ANDROID_ENTERPRISE,

        [EnumMember(Value = "INTUNE_APP_PROTECTION_MANAGEMENT_TYPE_ANDROID_ENTERPRISE_DEDICATED_DEVICES_WITH_AZURE_AD_SHARED_MODE")]
        INTUNE_APP_PROTECTION_MANAGEMENT_TYPE_ANDROID_ENTERPRISE_DEDICATED_DEVICES_WITH_AZURE_AD_SHARED_MODE,

        [EnumMember(Value = "INTUNE_APP_PROTECTION_MANAGEMENT_TYPE_ANDROID_OPEN_SOURCE_PROJECT_USERLESS")]
        INTUNE_APP_PROTECTION_MANAGEMENT_TYPE_ANDROID_OPEN_SOURCE_PROJECT_USERLESS,

        [EnumMember(Value = "INTUNE_APP_PROTECTION_MANAGEMENT_TYPE_ANDROID_OPEN_SOURCE_PROJECT_USER_ASSOCIATED")]
        INTUNE_APP_PROTECTION_MANAGEMENT_TYPE_ANDROID_OPEN_SOURCE_PROJECT_USER_ASSOCIATED,

        [EnumMember(Value = "INTUNE_APP_PROTECTION_MANAGEMENT_TYPE_MDM")]
        INTUNE_APP_PROTECTION_MANAGEMENT_TYPE_MDM,

        [EnumMember(Value = "INTUNE_APP_PROTECTION_MANAGEMENT_TYPE_NOT_AVAILABLE")]
        INTUNE_APP_PROTECTION_MANAGEMENT_TYPE_NOT_AVAILABLE,

        [EnumMember(Value = "INTUNE_APP_PROTECTION_MANAGEMENT_TYPE_UNKNOWN")]
        INTUNE_APP_PROTECTION_MANAGEMENT_TYPE_UNKNOWN,

        [EnumMember(Value = "INTUNE_APP_PROTECTION_MANAGEMENT_TYPE_UNMANAGED")]
        INTUNE_APP_PROTECTION_MANAGEMENT_TYPE_UNMANAGED,

        [EnumMember(Value = "INTUNE_APP_PROTECTION_MANAGEMENT_TYPE_WITHOUT_ENROLLMENT")]
        INTUNE_APP_PROTECTION_MANAGEMENT_TYPE_WITHOUT_ENROLLMENT,

        [EnumMember(Value = "INTUNE_APP_PROTECTION_MANAGEMENT_TYPE_WITH_ENROLLMENT")]
        INTUNE_APP_PROTECTION_MANAGEMENT_TYPE_WITH_ENROLLMENT


    } // enum IntuneAppProtectionManagementType

} // namespace RubrikSecurityCloud.Types