// RemediationDisabledReason.cs
//
// This generated file is part of the Rubrik PowerShell SDK.
// Manual changes to this file may be lost.

#nullable enable
using System;
using System.Collections.Generic;
using System.Text;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace RubrikSecurityCloud.Types
{
    public enum RemediationDisabledReason
    {
        [EnumMember(Value = "UNKNOWN")]
        UNKNOWN,

        [EnumMember(Value = "REMEDIATION_DISABLED_REASON_ACCESS_REVOKED")]
        REMEDIATION_DISABLED_REASON_ACCESS_REVOKED,

        [EnumMember(Value = "REMEDIATION_DISABLED_REASON_ACTOR_TYPE_SYSTEM")]
        REMEDIATION_DISABLED_REASON_ACTOR_TYPE_SYSTEM,

        [EnumMember(Value = "REMEDIATION_DISABLED_REASON_AD_RISK_REMEDIATED")]
        REMEDIATION_DISABLED_REASON_AD_RISK_REMEDIATED,

        [EnumMember(Value = "REMEDIATION_DISABLED_REASON_BULK_REVERT_ACTIVITIES_REMEDIATED")]
        REMEDIATION_DISABLED_REASON_BULK_REVERT_ACTIVITIES_REMEDIATED,

        [EnumMember(Value = "REMEDIATION_DISABLED_REASON_CROSS_DOMAIN")]
        REMEDIATION_DISABLED_REASON_CROSS_DOMAIN,

        [EnumMember(Value = "REMEDIATION_DISABLED_REASON_DSPM_DISABLED")]
        REMEDIATION_DISABLED_REASON_DSPM_DISABLED,

        [EnumMember(Value = "REMEDIATION_DISABLED_REASON_ENTRA_ID_RISK_REMEDIATED")]
        REMEDIATION_DISABLED_REASON_ENTRA_ID_RISK_REMEDIATED,

        [EnumMember(Value = "REMEDIATION_DISABLED_REASON_GPO_ROLLBACK_REMEDIATED")]
        REMEDIATION_DISABLED_REASON_GPO_ROLLBACK_REMEDIATED,

        [EnumMember(Value = "REMEDIATION_DISABLED_REASON_MISSING_VIEW_DAG_PERMISSIONS")]
        REMEDIATION_DISABLED_REASON_MISSING_VIEW_DAG_PERMISSIONS,

        [EnumMember(Value = "REMEDIATION_DISABLED_REASON_NO_DIRECT_PERMISSIONS")]
        REMEDIATION_DISABLED_REASON_NO_DIRECT_PERMISSIONS,

        [EnumMember(Value = "REMEDIATION_DISABLED_REASON_POLICY_DELETED_OR_DISABLED")]
        REMEDIATION_DISABLED_REASON_POLICY_DELETED_OR_DISABLED,

        [EnumMember(Value = "REMEDIATION_DISABLED_REASON_POLICY_VIOLATION_NOT_ACTIVE")]
        REMEDIATION_DISABLED_REASON_POLICY_VIOLATION_NOT_ACTIVE,

        [EnumMember(Value = "REMEDIATION_DISABLED_REASON_REMEDIATION_IN_PROGRESS")]
        REMEDIATION_DISABLED_REASON_REMEDIATION_IN_PROGRESS,

        [EnumMember(Value = "REMEDIATION_DISABLED_REASON_SERVICE_NOT_CONNECTED")]
        REMEDIATION_DISABLED_REASON_SERVICE_NOT_CONNECTED,

        [EnumMember(Value = "REMEDIATION_DISABLED_REASON_SERVICE_NOT_INTEGRATED")]
        REMEDIATION_DISABLED_REASON_SERVICE_NOT_INTEGRATED,

        [EnumMember(Value = "REMEDIATION_DISABLED_REASON_TICKET_CREATED")]
        REMEDIATION_DISABLED_REASON_TICKET_CREATED,

        [EnumMember(Value = "REMEDIATION_DISABLED_REASON_UNSPECIFIED")]
        REMEDIATION_DISABLED_REASON_UNSPECIFIED


    } // enum RemediationDisabledReason

} // namespace RubrikSecurityCloud.Types