name: Build and Test SDK with Optional Service Account File

on:
  workflow_dispatch:
    branches:
      - devel
    inputs:
      service_account_json:
        description: "Optional Service Account JSON File (use instead of vault secret)"
        required: false
        default: ""

jobs:
  build-and-test:

    runs-on: self-hosted
    labels:
      - internal-linux-runner

    steps:
    # Checkout the repository code
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Check if service account JSON file is provided as input
    - name: Check for Provided Service Account JSON File
      id: check-input
      run: |
        if [ "${{ github.event.inputs.service_account_json }}" != "" ]; then
          echo "Service account JSON provided as input."
          echo "${{ github.event.inputs.service_account_json }}" > ${{ github.workspace }}/service_account.json
          echo "use_input_secret=true" >> $GITHUB_ENV
        else
          echo "No service account JSON provided. Will fetch from Vault."
          echo "use_input_secret=false" >> $GITHUB_ENV
        fi

    # Authenticate with Rubrik Vault (only if no service account JSON is provided)
    - name: Authenticate with Rubrik Vault
      if: env.use_input_secret == 'false'
      run: |
        export VAULT_ADDR="https://vault.rubrik-internal.com"
        vault login -method=github -token=${{ secrets.VAULT_GITHUB_TOKEN }}
      env:
        VAULT_GITHUB_TOKEN: ${{ secrets.VAULT_GITHUB_TOKEN }}

    # Fetch secrets from Rubrik Vault (only if no service account JSON is provided)
    - name: Fetch Secrets from Vault
      if: env.use_input_secret == 'false'
      run: |
        vault kv get -field=service_account_json secret/sdk/service_account > ${{ github.workspace }}/service_account.json
      env:
        VAULT_ADDR: "https://vault.rubrik-internal.com"

    # Verify the service account JSON file
    - name: Verify Service Account File
      run: |
        if [ -s ${{ github.workspace }}/service_account.json ]; then
          echo "Service account file is ready for use."
        else
          echo "Failed to prepare service account file." >&2
          exit 1
        fi

    # Install dependencies
    - name: Install Required Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https software-properties-common
      shell: bash

    # Install PowerShell
    - name: Install PowerShell
      run: |
        wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb" -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y powershell
      shell: bash

    # Install .NET SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    # Build the SDK
    - name: Build SDK
      run: pwsh -NoProfile -NonInteractive -File Utils/Build-RscSdk.ps1 -NoTests -CI

    # Test the SDK
    - name: Test SDK
      env:
        RSC_SERVICE_ACCOUNT_FILE: ${{ github.workspace }}/service_account.json
      run: pwsh -NoProfile -NonInteractive -File Utils/Test-RscSdk.ps1 -CI

    # Cleanup sensitive data
    - name: Cleanup Secrets
      run: rm -f ${{ github.workspace }}/service_account.json
      shell: bash

    # Archive build artifacts (Optional)
    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: ./artifacts
